import {
  Controller,
  Post,
  Body,
  Get,
  Param,
  Query,
  Res,
  UseGuards,
  HttpCode,
  HttpStatus,
  Delete,
  Patch,
  Request,
  UseInterceptors,
  UploadedFile,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { Response } from 'express';
import { FileInterceptor } from '@nestjs/platform-express';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiQuery,
  ApiConsumes,
} from '@nestjs/swagger';
import { AuthGuard } from '@nestjs/passport';
import { AiAssistantService } from './ai-assistant.service';
import { ChatRequestDto, ChatResponseDto } from './dto/chat.dto';

@ApiTags('AI Assistant')
@Controller('ai-assistant')
export class AiAssistantController {
  constructor(private readonly aiAssistantService: AiAssistantService) {}

  @Get('sessions')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({ summary: 'List user chat sessions' })
  @ApiQuery({ name: 'q', required: false, description: 'Search query for filtering chat sessions' })
  async listSessions(@Request() req: any, @Query('q') q?: string) {
    return this.aiAssistantService.listUserSessions(req.user.id || req.user.userId, q);
  }

  @Post('sessions')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Create new chat session' })
  async createSession(@Request() req: any, @Body('title') title?: string) {
    return this.aiAssistantService.createSession(req.user.id || req.user.userId, title);
  }

  @Delete('sessions/:id')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Delete a chat session' })
  async deleteSession(@Request() req: any, @Param('id') id: string) {
    return this.aiAssistantService.deleteSession(req.user.id || req.user.userId, id);
  }

  @Patch('sessions/:id')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Update chat session title' })
  async updateSessionTitle(
    @Request() req: any,
    @Param('id') id: string,
    @Body('title') title: string,
  ) {
    return this.aiAssistantService.updateSessionTitle(
      req.user.id || req.user.userId,
      id,
      title,
    );
  }

  @Get('quota')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get current user token quota and usage' })
  async getQuota(@Request() req: any) {
    return this.aiAssistantService.getUserQuota(req.user.id || req.user.userId);
  }

  @Post('upload')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @UseInterceptors(FileInterceptor('file'))
  @ApiConsumes('multipart/form-data')
  @ApiOperation({ summary: 'Upload file for AI agent analysis (copied to GoClaw workspace)' })
  async uploadFile(@Request() req: any, @UploadedFile() file: Express.Multer.File) {
    return this.aiAssistantService.uploadFileForAgent(req.user.id || req.user.userId, file);
  }

  @Get('download/:filename')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Download file generated by AI agent from GoClaw workspace' })
  async downloadAgentFile(
    @Request() req: any,
    @Param('filename') filename: string,
    @Res() res: Response,
  ) {
    // Prevent path traversal
    const sanitized = filename.replace(/[\/\\]/g, '').replace(/\.\./g, '');
    if (!sanitized || sanitized !== filename) {
      throw new BadRequestException('Invalid filename');
    }
    const filePath = this.aiAssistantService.getAgentFilePath(
      req.user.id || req.user.userId,
      sanitized,
    );
    if (!filePath) {
      throw new NotFoundException('File not found');
    }
    res.download(filePath, sanitized);
  }

  @Post('chat')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Send message to AI Assistant',
    description: 'Send a message to n8n AI chatbot and get response.',
  })
  @ApiResponse({
    status: 200,
    description: 'AI response generated successfully',
    type: ChatResponseDto,
  })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async chat(@Body() dto: ChatRequestDto): Promise<ChatResponseDto> {
    return this.aiAssistantService.processMessage(dto.message, dto.sessionId);
  }

  @Get('sessions/:sessionId')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({
    summary: 'Get chat session history',
    description: 'Retrieve the conversation history for a specific session.',
  })
  @ApiResponse({ status: 200, description: 'Session history retrieved' })
  @ApiResponse({ status: 404, description: 'Session not found' })
  getSessionHistory(@Param('sessionId') sessionId: string) {
    return this.aiAssistantService.getSessionHistory(sessionId);
  }

  // ============================================================
  // DATA RETRIEVAL ENDPOINTS (for n8n's HTTP Request tool)
  // These are internal endpoints - no auth required for n8n
  // ============================================================

  @Get('data/candidates')
  @ApiOperation({
    summary: 'Search candidates (for n8n)',
    description: 'Internal endpoint for n8n to retrieve candidate data.',
  })
  @ApiQuery({ name: 'query', required: false, description: 'Search query' })
  @ApiQuery({ name: 'limit', required: false, description: 'Max results' })
  async searchCandidates(
    @Query('query') query?: string,
    @Query('limit') limit?: string,
  ) {
    return this.aiAssistantService.searchCandidates(query, limit ? parseInt(limit) : 10);
  }

  @Get('data/applications')
  @ApiOperation({
    summary: 'Search applications (for n8n)',
    description: 'Internal endpoint for n8n to retrieve application data with AI screening results.',
  })
  @ApiQuery({ name: 'query', required: false, description: 'Search query' })
  @ApiQuery({ name: 'limit', required: false, description: 'Max results' })
  async searchApplications(
    @Query('query') query?: string,
    @Query('limit') limit?: string,
  ) {
    return this.aiAssistantService.searchApplications(query, limit ? parseInt(limit) : 10);
  }

  @Get('data/stats')
  @ApiOperation({
    summary: 'Get statistics (for n8n)',
    description: 'Internal endpoint for n8n to retrieve HR statistics.',
  })
  async getStats() {
    return this.aiAssistantService.getStats();
  }
}
